# playbooks\01_install_kubectl.yml

- name: Preparar nodo controlador con kubectl
  hosts: localhost
  become: true
  gather_facts: true

  vars:
    kubectl_version: "v1.33.0"
    kubectl_path: "/usr/local/bin/kubectl"

  tasks:
    - name: Instalar paquetes base
      package:
        name: [python3-pip, git, curl]
        state: present

    - name: Instalar módulo Python Kubernetes
      pip:
        name: kubernetes

    - name: Descargar kubectl {{ kubectl_version }}
      get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
        dest: /tmp/kubectl
        mode: "0755"

    - name: Mover kubectl a {{ kubectl_path }}
      copy:
        src: /tmp/kubectl
        dest: "{{ kubectl_path }}"
        remote_src: yes
        mode: "0755"